id: P000208
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །སྔ་འགྱུར་རྡོ་རྗེ་ཐེག་པའི་དབང་བསྐུར་སྤྱི་ལ་འཇུག་པའི་མཚམས་སྦྱོར་ཉུང་ངུར་བསྡུས་པ་བློ་གསལ་ངག་གི་འདོད་འཇོ་ཞེས་བྱ་བ་བཞུགས་སོ།།
  authors:
  - མཛད་པ་པོ། འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་པོ།
  layers:
  - book_title
  - author
  - quotation
  - yigchung
  id: SHE-RTD-011
web_metadata:
  title:
    en: The Illuminating and Wish Fulfilling Speech:A Short Introduction to the Empowerment
      Rituals of Vajrayana in General
    bo: སྔ་འགྱུར་རྡོ་རྗེ་ཐེག་པའི་དབང་བསྐུར་སྤྱི་ལ་འཇུག་པའི་མཚམས་སྦྱོར་ཉུང་ངུར་བསྡུས་པ་བློ་གསལ་ངག་གི་འདོད་འཇོ་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Treasury of Precious Termas–  Book 11
    bo: རིན་ཆེན་གཏེར་མཛོད།–  དེབ། ༡༡
  author:
    en: Jamyang Khyentse Wangpo
    bo: འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་པོ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-RTD-011
  category:
    en: Dharma Teaching
    bo: ཆོས་བསླབ་བྱ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-RTD-011.epub
  description:
    en: ''
    bo: ''
